version: '3.8'
services:
  backend:
    build: .
    ports: ["8000:8000"]
    env_file: .env
    depends_on: [postgres, redis]

  postgres:
    image: postgres:14
    env_file: .env
    volumes: [postgres_data:/var/lib/postgresql/data]

  redis:
    image: redis:7

volumes:
  postgres_data:
